/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_codebear_jnilib_Lib */

#ifndef _Included_com_codebear_jnilib_Lib
#define _Included_com_codebear_jnilib_Lib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_codebear_jnilib_Lib
 * Method:    getHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_codebear_jnilib_Lib_getHelloWorld__
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
